getsentry/sentry-mobile

- lib/screens/login/login_web_view.dart
Use the correct api client payload
> fix(login): Fix a compile time issue

- lib/api/sentry_api.dart
- lib/main.dart
- pubspec.lock
> Enha(flutterSDK): Bump Flutter SDK & Use sentry-mobile DSN

- lib/issue_screen.dart
- lib/issues.dart
- lib/main.dart
- lib/redux/reducers.dart
- lib/screens/login/login_screen.dart
- lib/screens/main/main_app_bar.dart
- lib/screens/main/main_bottom_navigation_bar.dart
- lib/screens/project_picker/project_picker.dart
- lib/screens/release_health/release_card.dart
- lib/screens/release_health/release_health.dart
- lib/screens/release_health/release_health_chart_row.dart
- lib/screens/settings/settings.dart
- lib/screens/settings/settings_header.dart
- pubspec.lock
- pubspec.yaml
> fix(formatting): Formatting of crash free session/users % broken

- lib/screens/main/main_screen.dart
> enha: Hide TabBar & Issues Screen 

- lib/screens/login/login_web_view.dart
> fix(login): Issues screen visible in web view

- lib/api/sentry_api.dart
> fix(api): Incorrect organization name

- lib/redux/middlewares.dart
- lib/redux/state/app_state.dart
- lib/screens/empty/empty_screen.dart
- lib/screens/release_health/release_health.dart
- lib/screens/release_health/release_health_view_model.dart
- lib/screens/settings/settings_view_model.dart
> feat(health): Show all projects in health screen if there are no bookmarks

- lib/screens/release_health/release_card.dart
> fix(ui): Missing line shadow in card

- lib/redux/middlewares.dart
- lib/screens/login/login_web_view.dart
> fix(login): Endless loading when signing in with Google

- lib/main.dart
- lib/redux/actions.dart
- lib/redux/middlewares.dart
- lib/redux/reducers.dart
- lib/screens/empty/empty_screen.dart
- lib/screens/release_health/release_card.dart
- lib/screens/release_health/release_health.dart
- lib/screens/release_health/release_health_chart_row.dart
- lib/screens/release_health/release_health_chart_row_view_model.dart
- lib/screens/release_health/release_health_view_model.dart
- lib/utils/throttled_action_collection.dart
- test/util/throttled_action_collection_test.dart
Closes #62 
Closes #63 
Closes #64
> Lazy loading of releases

- lib/redux/state/app_state.dart
- lib/screens/release_health/release_health.dart
- lib/screens/release_health/release_health_view_model.dart
- lib/screens/settings/settings_view_model.dart
> Fix(regression): Bookmarks not respected

- lib/screens/login/login_screen.dart
- lib/screens/login/login_web_view.dart
> Enha(login): Rename SignIn to Login

- lib/screens/project_picker/project_picker_view_model.dart
- lib/screens/settings/settings_view_model.dart
> Enha(settings): Show project slug instead of name

- lib/screens/release_health/release_card.dart
- lib/types/deploy.dart
- lib/types/deploy.g.dart
- lib/types/release.dart
- lib/utils/relative_date_time.dart
- test/util/relative_date_time_test.dart
> enha(release-card): Show environment and relative date instead of platforms

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Runner.entitlements
> fix(testflight): Fix Push Notifications Warning

- lib/api/sentry_api.dart
- lib/redux/actions.dart
- lib/redux/middlewares.dart
- lib/redux/reducers.dart
- lib/redux/state/app_state.dart
- lib/screens/settings/settings.dart
- lib/screens/settings/settings_view_model.dart
- lib/types/user.dart
- lib/types/user.g.dart
> enha(settings): Show Username/Email below Sign Out Button 

- ios/Runner/Info.plist
> enha(iOS): App Uses Non Extempt Encryption 

- lib/screens/release_health/release_health.dart
The ScrollView has now a min height matching the viewport height. See https://api.flutter.dev/flutter/widgets/SingleChildScrollView-class.html for reference.
Closes #87
> fix(health): Health bounding box scroll container cut off

- lib/main.dart
- lib/screens/login/login_screen.dart
- lib/screens/oboarding/onboarding_detail_screen.dart
- lib/screens/oboarding/onboarding_screen.dart
> feat(onboarding): Onboarding Screens

- lib/redux/reducers.dart
- lib/redux/state/app_state.dart
- lib/screens/health/health_screen_view_model.dart
- Always show all projects
- Show bookmarked first
Relates to #101
> enha(bookmarks): Move bookmarked projects to front

- lib/screens/login/login_web_view.dart
- pubspec.lock
- pubspec.yaml
> fix(login): Use correct user agent

- README.md
- android/.gitignore
- android/app/build.gradle
- android/build.gradle
- android/fastlane/Appfile
- android/fastlane/Fastfile
- android/fastlane/README.md
- android/gradle/wrapper/gradle-wrapper.properties
- ios/Podfile.lock
- pubspec.yaml
- Set correct application id
- Bump `gradle` versions
- Set `minSdkVersion`
- Aka Android 6.0
- This is the current default when creating a new project in Android Studio
- Setup fastlane for AAB upload to Google Play internal Chanel
> feat(setup): Setup Android for Release

- lib/main.dart
> enha(sentry-sdk): Setup production DSN

- lib/screens/project_picker/project_picker.dart
- lib/screens/project_picker/project_picker_item.dart
- lib/screens/project_picker/project_picker_view_model.dart
- Fix off by onw error when bookmarking
- Introduce empty text
> fix: Bookmark off by one error

- lib/redux/actions.dart
- lib/redux/middleware/local_storage_middleware.dart
- lib/redux/middleware/sentry_sdk_middleware.dart
- lib/redux/reducers.dart
- lib/screens/connect/connect_view_model.dart
> feat: Rename LoginAction to LoginSuccessAction

- lib/utils/relative_date_time.dart
- We were averaging the number of months, which could be off depending on the date.
- Took the relevant code from a dependency which is based on `moment.js`, which we use in the web version to display relative dates.
- Not used in the apps code for now, as we don't show previous releases for now.
Closes #152
> fix: Replace month difference estimation with calculation

- ios/Runner.xcodeproj/project.pbxproj
- Disable iPad support for now.
> feat: Disable iPad

- lib/screens/debug/sentry_flutter_screen.dart
- Add 'Sentry.captureEvent' and 'Sentry.captureMessage' to debug screen
When testing the behaviour of the SDK in relation to #155, following things were uncovered:
- Diable and Re-Enable SDK
- `Sentry.captureException`: The captured errors are reported multiple times to sentry if the SDK is diabled/enabled multiple times within the app. This could not be reproduced for 'Sentry.captureEvent', 'Sentry.captureMessage' and capturing of crashes in native code (iOS).
-  Disable Enabled SDK
- Native crashes were sent after SDK was disabled within the app. Of course, had to enable it after the app crashed to give the SDK a chance to upload, but they should not have been captured during disabled phase in the first place.
@marandaneto How should we best proceed here in regards to the SDK?
> feat: Send event and message from debug screen

- lib/screens/projects/projects_screen.dart
- Fix padding
- Center align text
Closes #165
> Fix: Padding in bookmarks screen empty view

- .github/workflows/build.yml
- analysis_options.yaml
- ios/Podfile.lock
- ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- lib/issue_screen.dart
- lib/screens/connect/connect_screen.dart
- lib/screens/debug/sentry_flutter_screen.dart
- lib/screens/empty/empty_screen.dart
- lib/screens/html/html_screen.dart
- lib/screens/onboarding/onboarding_consent_screen.dart
- lib/screens/projects/projects_screen.dart
- lib/screens/settings/settings.dart
- pubspec.lock
- pubspec.yaml
- Replace deprecated Widgets
- Bump flutter version in GitHub action `build.yaml`
- Update broken statusbar Colors
- Fix other warnings
Only the minimal set of dependencies was updated so that everything is building correctly. Null-safety is not yet enabled.
Closes #159
> feat: Upgrade to Flutter 2

- .github/workflows/build.yml
- lib/screens/debug/sentry_flutter_screen.dart
- Fix Flutter 2 deprecations
- Bump flutter version to 2.0.2 in Github Action
> Fix: Deprecations

- lib/redux/middleware/sentry_api_middleware.dart
- lib/screens/health/health_screen.dart
> feat: Error screen when fetching projects with sessions fails

- lib/redux/reducers.dart
- lib/redux/state/app_state.dart
- lib/screens/health/health_screen.dart
- lib/screens/health/health_screen_view_model.dart
Closes #172
Also thought about showing a global banner, but for now we just check if the error has to do with connectivity and show it inline.
>  feat: Info when calls fail due to connectivity issues 

- lib/redux/state/app_state.dart
- lib/screens/license/license_screen.dart
- lib/screens/settings/settings.dart
- pubspec.lock
- Show license screen from settings
Closes #187
> feat: License Screen

- lib/redux/state/app_state.dart
- pubspec.lock
- pubspec.yaml
> Fix: pubspec.yaml Improvements

- ios/Podfile.lock
- pubspec.lock
- pubspec.yaml
- Use current Sentry Flutter Beta
> Use Sentry Flutter 5.1.0-beta.1

- lib/screens/health/health_screen.dart
- Reload projects on resume if there is an error
Closes #185
> Fix error screen on resume

- ios/Podfile.lock
- lib/redux/middleware/sentry_sdk_middleware.dart
- pubspec.lock
- pubspec.yaml
Closes https://github.com/getsentry/sentry-mobile/issues/191
Also improves formatting in that file.
> Only consider `sentry_mobile` as in app frames

- CHANGELOG.md
- pubspec.lock
- pubspec.yaml
> Bump Sentry Flutter

- CHANGELOG.md
- pubspec.lock
- Dependencies were not matching
> Repair Lock File

- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- lib/redux/global/global_reducer.dart
- lib/redux/global/global_state.dart
- lib/redux/state/session_state.dart
- lib/screens/chart/line_chart.dart
- lib/screens/health/health_screen_view_model.dart
- lib/screens/health/project_card.dart
- lib/screens/onboarding/onboarding_info_screen.dart
- lib/screens/shared/link_rich_text.dart
- lib/utils/sentry_colors.dart
- pubspec.lock
- test/screens/release_health/sessions_chart_row_view_model_test.dart
We get many negative reviews that their projects are not showing up in the app. This was due to the fact that we decided to only show projects with session data.
- We now show all projects, not just the ones with session data.
- The ones without session data link to `https://docs.sentry.io/product/releases/health/`
> Show All Projects

- lib/redux/middleware/sentry_sdk_middleware.dart
We're far for using all our quota
> sample all traces
